#!/usr/bin/env bash
echo hello

for (( i = 0; i < 10; i++ )); do
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    echo "asdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdjaasdja"
    sleep 1
done
